import { Board } from "@/types";

export const TEMPLATE_SUDOKU_1: Board = [
	[
		{
			x: 0,
			y: 0,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 0,
			value: "8",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 0,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 0,
			value: "5",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 0,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 0,
			value: "1",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 0,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 0,
			value: "3",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 0,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 1,
			value: "6",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 1,
			value: "7",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 1,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 2,
			value: "5",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 2,
			value: "4",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 2,
			value: "9",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 2,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 3,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 3,
			value: "1",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 3,
			value: "3",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 3,
			value: "9",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 3,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 3,
			value: "6",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 3,
			value: "4",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 3,
			value: "7",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 3,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 4,
			value: "4",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 4,
			value: "6",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 4,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 5,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 5,
			value: "2",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 5,
			value: "7",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 5,
			value: "4",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 5,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 5,
			value: "3",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 5,
			value: "8",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 5,
			value: "5",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 5,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 6,
			value: "7",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 6,
			value: "5",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 6,
			value: "4",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 6,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 7,
			value: "8",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 7,
			value: "5",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 7,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
	[
		{
			x: 0,
			y: 8,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 1,
			y: 8,
			value: "3",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 2,
			y: 8,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 3,
			y: 8,
			value: "2",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 4,
			y: 8,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 5,
			y: 8,
			value: "8",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 6,
			y: 8,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 7,
			y: 8,
			value: "6",
			potentialValues: [],
			color: "black",
			backgroundColor: "",
			potentialCell: true,
		},
		{
			x: 8,
			y: 8,
			value: "",
			potentialValues: [],
			color: "",
			backgroundColor: "",
			potentialCell: true,
		},
	],
];
